apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-html
          hostPath:
            path: /tmp/html
            type: DirectoryOrCreate
      containers:
        - name: nginx
          image: nginx:1.15
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      nodePort: 30880
  type: NodePort
