apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  minReadySeconds: 30
  selector:
    matchLabels:
      app: webapp
      release: "0.5"
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: webapp
        release: "0.5"
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---

apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
    - name: queue
      image: richardchesterwood/k8s-fleetman-queue:release1
